### ISSUE TITLE
Upgrade ESLint 8 -> 10 and migrate to flat config

### ISSUE THREAD

**Issue by Jamyn** [Jamyn/dispatch#248]
ESLint is pinned at `^8.57.0`. npm marks both 8.57.1 and 9.39.5 `"This version is no longer supported"`; current is 10.8.1. This is the real deadline in the frontend toolchain.

The blocker is gone. `eslint-plugin-prettier@4.2.5` crashed on ESLint 10 with `TypeError: Error while loading rule 'prettier/prettier': context.getSourceCode is not a function` (v4 has shipped no code since 2022 — 4.2.5 is byte-identical to 4.2.1). #189 moved to v5.5.6, which is verified working on ESLint 10.8.1 *and* on prettier 2, so this migration does not depend on #247.

Work required:

- `.eslintrc.js` -> `eslint.config.js` flat config. ESLint 10 does not read eslintrc.
- Rewire `eslint-plugin-local-rules` / `eslint-local-rules.js`, and the `plugin:prettier/recommended` + `plugin:vue/strongly-recommended` + `plugin:vuetify/base` extends, into flat equivalents.
- Bump `eslint-config-prettier` `^8.10.0` -> `^10.1.8`. `eslint-plugin-prettier@5` peers `">= 7.0.0 <10.0.0 || >=10.1.0"`, so 10.0.x is excluded but 10.1+ is fine.
- Drop `--ext .js,.vue` from the `lint`/`lint:fix` scripts; flat config selects files itself.
- Confirm each remaining plugin supports 10 before bumping: `eslint-plugin-vue@^10.10.0`, `eslint-plugin-vuetify@^2.7.2`, `@typescript-eslint/*@^8.66.0`, `vue-eslint-parser@^10.3.0`.

`src/tests/eslintPrettierRule.spec.js` constructs `new ESLint()` and relies on config discovery, so it will need the flat-config constructor form. It is also the guard that proves the prettier integration survived the migration — keep it passing rather than adapting it away.
